// Generated by gencpp from file dmp/DMPPointStamp.msg
// DO NOT EDIT!


#ifndef DMP_MESSAGE_DMPPOINTSTAMP_H
#define DMP_MESSAGE_DMPPOINTSTAMP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dmp
{
template <class ContainerAllocator>
struct DMPPointStamp_
{
  typedef DMPPointStamp_<ContainerAllocator> Type;

  DMPPointStamp_()
    : head()
    , positions(0.0)  {
    }
  DMPPointStamp_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , positions(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef double _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::dmp::DMPPointStamp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dmp::DMPPointStamp_<ContainerAllocator> const> ConstPtr;

}; // struct DMPPointStamp_

typedef ::dmp::DMPPointStamp_<std::allocator<void> > DMPPointStamp;

typedef boost::shared_ptr< ::dmp::DMPPointStamp > DMPPointStampPtr;
typedef boost::shared_ptr< ::dmp::DMPPointStamp const> DMPPointStampConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dmp::DMPPointStamp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dmp::DMPPointStamp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dmp::DMPPointStamp_<ContainerAllocator1> & lhs, const ::dmp::DMPPointStamp_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dmp::DMPPointStamp_<ContainerAllocator1> & lhs, const ::dmp::DMPPointStamp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dmp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dmp::DMPPointStamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmp::DMPPointStamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::DMPPointStamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::DMPPointStamp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::DMPPointStamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::DMPPointStamp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dmp::DMPPointStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db08163e791135724278324162c51a67";
  }

  static const char* value(const ::dmp::DMPPointStamp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb08163e79113572ULL;
  static const uint64_t static_value2 = 0x4278324162c51a67ULL;
};

template<class ContainerAllocator>
struct DataType< ::dmp::DMPPointStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dmp/DMPPointStamp";
  }

  static const char* value(const ::dmp::DMPPointStamp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dmp::DMPPointStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header head\n"
"float64 positions\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dmp::DMPPointStamp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dmp::DMPPointStamp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DMPPointStamp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dmp::DMPPointStamp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dmp::DMPPointStamp_<ContainerAllocator>& v)
  {
    s << indent << "head: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    s << indent << "positions: ";
    Printer<double>::stream(s, indent + "  ", v.positions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMP_MESSAGE_DMPPOINTSTAMP_H
