// Generated by gencpp from file dmp/GetDMPStepPlan.msg
// DO NOT EDIT!


#ifndef DMP_MESSAGE_GETDMPSTEPPLAN_H
#define DMP_MESSAGE_GETDMPSTEPPLAN_H

#include <ros/service_traits.h>


#include <dmp/GetDMPStepPlanRequest.h>
#include <dmp/GetDMPStepPlanResponse.h>


namespace dmp
{

struct GetDMPStepPlan
{

typedef GetDMPStepPlanRequest Request;
typedef GetDMPStepPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDMPStepPlan
} // namespace dmp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dmp::GetDMPStepPlan > {
  static const char* value()
  {
    return "5cb36999dd0228bf3a5de0dcd217f277";
  }

  static const char* value(const ::dmp::GetDMPStepPlan&) { return value(); }
};

template<>
struct DataType< ::dmp::GetDMPStepPlan > {
  static const char* value()
  {
    return "dmp/GetDMPStepPlan";
  }

  static const char* value(const ::dmp::GetDMPStepPlan&) { return value(); }
};


// service_traits::MD5Sum< ::dmp::GetDMPStepPlanRequest> should match
// service_traits::MD5Sum< ::dmp::GetDMPStepPlan >
template<>
struct MD5Sum< ::dmp::GetDMPStepPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dmp::GetDMPStepPlan >::value();
  }
  static const char* value(const ::dmp::GetDMPStepPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dmp::GetDMPStepPlanRequest> should match
// service_traits::DataType< ::dmp::GetDMPStepPlan >
template<>
struct DataType< ::dmp::GetDMPStepPlanRequest>
{
  static const char* value()
  {
    return DataType< ::dmp::GetDMPStepPlan >::value();
  }
  static const char* value(const ::dmp::GetDMPStepPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dmp::GetDMPStepPlanResponse> should match
// service_traits::MD5Sum< ::dmp::GetDMPStepPlan >
template<>
struct MD5Sum< ::dmp::GetDMPStepPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dmp::GetDMPStepPlan >::value();
  }
  static const char* value(const ::dmp::GetDMPStepPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dmp::GetDMPStepPlanResponse> should match
// service_traits::DataType< ::dmp::GetDMPStepPlan >
template<>
struct DataType< ::dmp::GetDMPStepPlanResponse>
{
  static const char* value()
  {
    return DataType< ::dmp::GetDMPStepPlan >::value();
  }
  static const char* value(const ::dmp::GetDMPStepPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DMP_MESSAGE_GETDMPSTEPPLAN_H
