// Generated by gencpp from file dmp/GoalToPath.msg
// DO NOT EDIT!


#ifndef DMP_MESSAGE_GOALTOPATH_H
#define DMP_MESSAGE_GOALTOPATH_H

#include <ros/service_traits.h>


#include <dmp/GoalToPathRequest.h>
#include <dmp/GoalToPathResponse.h>


namespace dmp
{

struct GoalToPath
{

typedef GoalToPathRequest Request;
typedef GoalToPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalToPath
} // namespace dmp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dmp::GoalToPath > {
  static const char* value()
  {
    return "61b7759cacf0fb0b224df3e235dda576";
  }

  static const char* value(const ::dmp::GoalToPath&) { return value(); }
};

template<>
struct DataType< ::dmp::GoalToPath > {
  static const char* value()
  {
    return "dmp/GoalToPath";
  }

  static const char* value(const ::dmp::GoalToPath&) { return value(); }
};


// service_traits::MD5Sum< ::dmp::GoalToPathRequest> should match
// service_traits::MD5Sum< ::dmp::GoalToPath >
template<>
struct MD5Sum< ::dmp::GoalToPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dmp::GoalToPath >::value();
  }
  static const char* value(const ::dmp::GoalToPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dmp::GoalToPathRequest> should match
// service_traits::DataType< ::dmp::GoalToPath >
template<>
struct DataType< ::dmp::GoalToPathRequest>
{
  static const char* value()
  {
    return DataType< ::dmp::GoalToPath >::value();
  }
  static const char* value(const ::dmp::GoalToPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dmp::GoalToPathResponse> should match
// service_traits::MD5Sum< ::dmp::GoalToPath >
template<>
struct MD5Sum< ::dmp::GoalToPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dmp::GoalToPath >::value();
  }
  static const char* value(const ::dmp::GoalToPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dmp::GoalToPathResponse> should match
// service_traits::DataType< ::dmp::GoalToPath >
template<>
struct DataType< ::dmp::GoalToPathResponse>
{
  static const char* value()
  {
    return DataType< ::dmp::GoalToPath >::value();
  }
  static const char* value(const ::dmp::GoalToPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DMP_MESSAGE_GOALTOPATH_H
