// Generated by gencpp from file dmp/GoalToPathResponse.msg
// DO NOT EDIT!


#ifndef DMP_MESSAGE_GOALTOPATHRESPONSE_H
#define DMP_MESSAGE_GOALTOPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace dmp
{
template <class ContainerAllocator>
struct GoalToPathResponse_
{
  typedef GoalToPathResponse_<ContainerAllocator> Type;

  GoalToPathResponse_()
    : Path()  {
    }
  GoalToPathResponse_(const ContainerAllocator& _alloc)
    : Path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _Path_type;
  _Path_type Path;





  typedef boost::shared_ptr< ::dmp::GoalToPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dmp::GoalToPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalToPathResponse_

typedef ::dmp::GoalToPathResponse_<std::allocator<void> > GoalToPathResponse;

typedef boost::shared_ptr< ::dmp::GoalToPathResponse > GoalToPathResponsePtr;
typedef boost::shared_ptr< ::dmp::GoalToPathResponse const> GoalToPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dmp::GoalToPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dmp::GoalToPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dmp::GoalToPathResponse_<ContainerAllocator1> & lhs, const ::dmp::GoalToPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Path == rhs.Path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dmp::GoalToPathResponse_<ContainerAllocator1> & lhs, const ::dmp::GoalToPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dmp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dmp::GoalToPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmp::GoalToPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::GoalToPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::GoalToPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::GoalToPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::GoalToPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dmp::GoalToPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24fae27c1f7b7e0732c341610d3780f7";
  }

  static const char* value(const ::dmp::GoalToPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24fae27c1f7b7e07ULL;
  static const uint64_t static_value2 = 0x32c341610d3780f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::dmp::GoalToPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dmp/GoalToPathResponse";
  }

  static const char* value(const ::dmp::GoalToPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dmp::GoalToPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"nav_msgs/Path Path\n"
"\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dmp::GoalToPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dmp::GoalToPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalToPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dmp::GoalToPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dmp::GoalToPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "Path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.Path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMP_MESSAGE_GOALTOPATHRESPONSE_H
