// Generated by gencpp from file epos_msgs/MotorStates.msg
// DO NOT EDIT!


#ifndef EPOS_MSGS_MESSAGE_MOTORSTATES_H
#define EPOS_MSGS_MESSAGE_MOTORSTATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <epos_msgs/MotorState.h>

namespace epos_msgs
{
template <class ContainerAllocator>
struct MotorStates_
{
  typedef MotorStates_<ContainerAllocator> Type;

  MotorStates_()
    : header()
    , states()  {
    }
  MotorStates_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , states(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::epos_msgs::MotorState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::epos_msgs::MotorState_<ContainerAllocator> >> _states_type;
  _states_type states;





  typedef boost::shared_ptr< ::epos_msgs::MotorStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos_msgs::MotorStates_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStates_

typedef ::epos_msgs::MotorStates_<std::allocator<void> > MotorStates;

typedef boost::shared_ptr< ::epos_msgs::MotorStates > MotorStatesPtr;
typedef boost::shared_ptr< ::epos_msgs::MotorStates const> MotorStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos_msgs::MotorStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos_msgs::MotorStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::epos_msgs::MotorStates_<ContainerAllocator1> & lhs, const ::epos_msgs::MotorStates_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.states == rhs.states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::epos_msgs::MotorStates_<ContainerAllocator1> & lhs, const ::epos_msgs::MotorStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace epos_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::epos_msgs::MotorStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos_msgs::MotorStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos_msgs::MotorStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos_msgs::MotorStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos_msgs::MotorStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos_msgs::MotorStates_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos_msgs::MotorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ad89420af0daf166bb737efa2555173";
  }

  static const char* value(const ::epos_msgs::MotorStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ad89420af0daf16ULL;
  static const uint64_t static_value2 = 0x6bb737efa2555173ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos_msgs::MotorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos_msgs/MotorStates";
  }

  static const char* value(const ::epos_msgs::MotorStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos_msgs::MotorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"\n"
"MotorState[] states\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: epos_msgs/MotorState\n"
"\n"
"Header header\n"
"\n"
"string motor_name\n"
"\n"
"float64 position\n"
"float64 velocity\n"
"float64 current\n"
;
  }

  static const char* value(const ::epos_msgs::MotorStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos_msgs::MotorStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos_msgs::MotorStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos_msgs::MotorStates_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::epos_msgs::MotorState_<ContainerAllocator> >::stream(s, indent + "    ", v.states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS_MSGS_MESSAGE_MOTORSTATES_H
